### ISSUE TITLE
Add roadmap of the project

### ISSUE THREAD

**Issue by shift-d** [noib3/nvim-oxi#1]
Some people like me would like to contribute, but sadly, I dont know what to start with. Having somekind of a todo/gh project/roadmap would be great, so more people would contribute.

**Comment by max397574** [comment]
one with the new beta projects perhaps

**Comment by noib3** [comment]
[Done](https://github.com/noib3/nvim-oxi/projects/1). I'll add more specific and targeted issues to the roadmap as I think of them.
