### ISSUE TITLE
This crate is causing neovim to crash on the latest commit

### ISSUE THREAD

**Issue by augustocdias** [noib3/nvim-oxi#103]
When using neovim nightly it is crashing on startup. More details here: https://github.com/neovim/neovim/issues/22654

**Comment by clason** [comment]
Wait, didn't you claim you were using Neovim 0.8.3 on that issue?

**Comment by willothy** [comment]
I am experiencing this as well. It might be something I'm doing, but it seems to happen at random so I'm not sure.

**Comment by willothy** [comment]
yay!

**Comment by noib3** [comment]
@willothy there are still some issues when linking against Neovim nightly, some of which should be fixed by https://github.com/noib3/nvim-oxi/pull/100. Please lmk if you encounter any.

**Comment by willothy** [comment]
For sure, will do. Thanks!
