### ISSUE TITLE
Can't build this repository on Windows.

### ISSUE THREAD

**Issue by shift-d** [noib3/nvim-oxi#12]
Rustc: `rustc 1.59.0 (9d1b2106e 2022-02-23)`
Cargo: `cargo 1.59.0 (49d8809dc 2022-02-10)`
NeoVim: `NVIM v0.8.0-dev+296-g307c5c63e`
Error: 
![изображение](https://user-images.githubusercontent.com/53366878/170449978-1fab49b7-0a90-4eb5-83e4-9bf672272e80.png)

Translation of some parts of error message:
ссылка на неразрешённый внешний символ -> link to forbidden external symbol
в функции -> in function
неразрешенных внешних элементов -> forbidden external elements
создается библиотека -> creating a library

**Comment by noib3** [comment]
Try adding a file in `.cargo/config` with [this](https://github.com/noib3/nvim-compleet/blob/master/.cargo/config) config, changing `apple-darwin` for whatever the architecture name of windows is (I assume just `windows`).

**Comment by shift-d** [comment]
.cargo/config:
```toml
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]

[target.aarch64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

now i cant even build dependency crates
![изображение](https://user-images.githubusercontent.com/53366878/170460500-08e1a459-720e-4c3f-b977-635d256cb4cb.png)

**Comment by noib3** [comment]
I'm not on Windows so I'm not sure how to help. Try googling those `LNK1120` and `LNK4044` errors?

**Comment by turboladen** [comment]
FWIW, I'm unable to build `master` on MacOS 12.4 with neovim 0.7.0.:

```
  = note: Undefined symbols for architecture arm64:
            "_nvim_buf_set_lines", referenced from:
                nvim_oxi::api::buffer::buffer::Buffer::set_lines::hdd424ae77f2153d5 in nvim_oxi.oxwr7faqjkh86jf.rcgu.o
            "_nvim_buf_get_option", referenced from:
                nvim_oxi::api::buffer::buffer::Buffer::get_option::hc21c9e32db803a65 in nvim_oxi.oxwr7faqjkh86jf.rcgu.o
            "_lua_getfield", referenced from:
                nvim_oxi::toplevel::toplevel::print::_$u7b$$u7b$closure$u7d$$u7d$::h192461af31742870 in nvim_oxi.437f80zcb8hopa87.rcgu.o
            "_lua_pushstring", referenced from:
                nvim_oxi::toplevel::toplevel::print::_$u7b$$u7b$closure$u7d$$u7d$::h192461af31742870 in nvim_oxi.437f80zcb8hopa87.rcgu.o
            "_lua_call", referenced from:
                nvim_oxi::toplevel::toplevel::print::_$u7b$$u7b$closure$u7d$$u7d$::h192461af31742870 in nvim_oxi.437f80zcb8hopa87.rcgu.o
            "_lua_pushlstring", referenced from:
                _$LT$T$u20$as$u20$nvim_oxi..lua..lua..LuaPushable$GT$::push::hb8d40955a63a2f77 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_nvim_buf_set_option", referenced from:
                nvim_oxi::api::buffer::buffer::Buffer::set_option::h98bab8ca4aa681fb in nvim_oxi.oxwr7faqjkh86jf.rcgu.o
            "_lua_pushboolean", referenced from:
                _$LT$T$u20$as$u20$nvim_oxi..lua..lua..LuaPushable$GT$::push::hb8d40955a63a2f77 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_lua_newuserdata", referenced from:
                nvim_oxi::lua::lua::once_to_luaref::_$u7b$$u7b$closure$u7d$$u7d$::hfd28961c531f93e9 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_nvim_buf_get_var", referenced from:
                nvim_oxi::api::buffer::buffer::Buffer::get_var::he819f2a686c150cd in nvim_oxi.oxwr7faqjkh86jf.rcgu.o
            "_lua_pushinteger", referenced from:
                _$LT$T$u20$as$u20$nvim_oxi..lua..lua..LuaPushable$GT$::push::hb8d40955a63a2f77 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_lua_pushnil", referenced from:
                _$LT$T$u20$as$u20$nvim_oxi..lua..lua..LuaPushable$GT$::push::hb8d40955a63a2f77 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_lua_pushnumber", referenced from:
                _$LT$T$u20$as$u20$nvim_oxi..lua..lua..LuaPushable$GT$::push::hb8d40955a63a2f77 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_luaL_ref", referenced from:
                nvim_oxi::lua::lua::once_to_luaref::_$u7b$$u7b$closure$u7d$$u7d$::hfd28961c531f93e9 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_nvim_buf_call", referenced from:
                nvim_oxi::api::buffer::buffer::Buffer::call::he260fd1adc497b3f in nvim_oxi.oxwr7faqjkh86jf.rcgu.o
            "_lua_touserdata", referenced from:
                nvim_oxi::lua::lua::once_to_luaref::c_fun::h08797fa95de8af92 in nvim_oxi.1n6u1fw4hsiiqv27.rcgu.o
            "_nvim_get_current_buf", referenced from:
                nvim_oxi::api::global::global::get_current_buf::h4521663ad3b8687f in nvim_oxi.3ivdcb1ywicb5r0o.rcgu.o
            "_nvim_create_buf", referenced from:
                nvim_oxi::api::global::global::create_buf::h8eda9da327b87f79 in nvim_oxi.3ivdcb1ywicb5r0o.rcgu.o
            "_nvim_get_mode", referenced from:
                nvim_oxi::api::global::global::get_mode::h1ab1b1788af7b16d in nvim_oxi.3ivdcb1ywicb5r0o.rcgu.o
            "_nvim_buf_set_var", referenced from:
                nvim_oxi::api::buffer::buffer::Buffer::set_var::hcbd15dcb6f0d8b10 in nvim_oxi.oxwr7faqjkh86jf.rcgu.o
            "_lua_pushcclosure", referenced from:
                nvim_oxi::lua::lua::once_to_luaref::_$u7b$$u7b$closure$u7d$$u7d$::hfd28961c531f93e9 in nvim_oxi.3sn6kj4i5c0x2x71.rcgu.o
            "_nvim_buf_get_name", referenced from:
                nvim_oxi::api::buffer::buffer::Buffer::get_name::h5ebd92b2dd787a52 in nvim_oxi.17x8afrijgrogobk.rcgu.o
          ld: symbol(s) not found for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


warning: `nvim-oxi` (lib) generated 94 warnings
error: could not compile `nvim-oxi` due to previous error; 94 warnings emitted
```

**Comment by turboladen** [comment]
OMG, sorry, I'm a dummy. I missed/forgot about the `.cargo/config` bit. What do you think about just committing that to the repo since it's a requirement to build?

**Comment by noib3** [comment]
@turboladen I hadn't added because that's only needed while the crate is used directly for testing, so it'll eventually be removed. But I guess you're right, it makes sense to add it for now.

**Comment by noib3** [comment]
@shift-d did you get it to build?

**Comment by shift-d** [comment]
@noib3 sorry, i forgot to answer you, but it seems that i need to have some lua libraries installed. do you use lua 5.1 or luajit? i want to try installing library you are dependant on and build crate again

**Comment by noib3** [comment]
@shift-d there are no Lua libraries to install, all the `lua_*` C functions are already exported by Neovim. You should be able to build it with a simple `cargo build`.

**Comment by shift-d** [comment]
it seems that neovim does not export lua_ functions for windows

**Comment by shift-d** [comment]
or cargo cant find them

**Comment by noib3** [comment]
> it seems that neovim does not export lua_ functions for windows

I may be wrong but I don't think that's the problem. I think the issue is that cargo is complaining that all the `lua_*` symbols are not present at *compile* time. The solution (at least on macOS) is to tell cargo that they will be available at runtime when the library gets loaded by Neovim, with [this](https://github.com/noib3/nvim-compleet/blob/master/.cargo/config) config.

**Comment by shift-d** [comment]
welp, welp, welp

good news: now the crate is able to compile
bad news: ``error: could not compile `nvim-oxi` due to 284 previous errors``

ive marked some crates as cdylib to check if that will help to compile on windows, and... it almost worked
check out fix/windows-compilation on my fork

**Comment by shift-d** [comment]
Huh, I've rebuilt everything, and it seems now that entire repo is compiles only with one fix - using std::os::unix on linux and using std::os::windows on windows

**Comment by shift-d** [comment]
@noib3 it seems that #16 will resolve this issue, but it solves different bug caused by using `std::os::unix` without `cfg` attribute

**Comment by shift-d** [comment]
@noib3 
bad news, after i tried to build oxi-tests, the issue is still present
it seems that the reason why issue was not present when i tried to reproduce it was the fact that you moved tests to oxi-tests
