### ISSUE TITLE
[Windows][Powershell7] linking with `link.exe` failed: exit code: 1120

### ISSUE THREAD

**Issue by searleser97** [noib3/nvim-oxi#120]
![image](https://github.com/noib3/nvim-oxi/assets/5056411/4f57e54f-ea09-4916-891b-69e8676afb4f)

**Comment by noib3** [comment]
Building and linking in Windows has been a problem for a long time. (Un?)fortunately I don't have access to a Windows machine to try to figure out why.

Closing in favor of #77.

**Comment by searleser97** [comment]
so basically your library can't be used in windows as of now right ? :( cause building is a requirement to make it work :(

**Comment by noib3** [comment]
Building works, linking apparently doesn't. I assume it's a matter of appropriately configuring Cargo via the `/.cargo/config.toml` file. If you're on Windows and can get it to work I'd be happy to merge a PR.

**Comment by searleser97** [comment]
I am trying to build it, and I get the Link error, so can't really build anything, this is how my config.toml file looks
```toml
[target.x86_64-pc-windows-msvc]
rustflags = [
  "-C", "link-arg=-undefined",
  "-C", "link-arg=dynamic_lookup",
]
```

**Comment by searleser97** [comment]
Looks like after adding a link to "lua51.lib" it is able to resolve the links for some functions, but still 105 (originally 133) of them are unresolved 

Added the following to `build.rs`

```rs
fn main() {
  println!("cargo:rustc-link-search=E:\\forks\\luajit\\src");
  println!("cargo:rustc-link-lib=lua51");
}
```
