### ISSUE TITLE
https://github.com/tami5/xbase

### ISSUE THREAD

**Issue by kuator** [noib3/nvim-oxi#13]
Thought you would be interested

**Comment by noib3** [comment]
By looking at the dependencies it seems like they're using RPC (`nvim-rs`) or Lua (`mlua`). Also I believe @tami5 had [asked me](https://github.com/noib3/nvim-compleet/issues/15) to extract nvim-bindings to its own repo. So yeah, `nvim-oxi` could definitely be used in `xbase` once it's ready.

**Comment by tami5** [comment]
😍😍 looking forward to migrate. Great work
