### ISSUE TITLE
Add Installation Instructions

### ISSUE THREAD

**Issue by JasonGrace2282** [noib3/nvim-oxi#133]
It would be nice if it was in the README.md
If manual installation is needed, an archlinux PKGBUILD would also be very helpful.

**Comment by noib3** [comment]
Those instructions are in [`examples/README.md`](https://github.com/noib3/nvim-oxi/tree/main/examples#crate-setup), which the main `README.md` links to. For the PKGBUILD, it's up to the plugin authors to provide it since every setup is a bit different.
