### ISSUE TITLE
f32 conversion issue?

### ISSUE THREAD

**Issue by melMass** [noib3/nvim-oxi#152]
Hi,

Thanks for this project.
When I use f32 as a struct member it's deserialized as a random int (probably some address? Although it changes at each call). Using f64 works properly.

- **⛔ with f32 (case 1)**:

```sh
lua | Options before rust: { amplify = 0.5, demo = true }
rust | Merging default options with other: OptionsOpt { amplify: Some(0.5), demo: Some(true) }
rust | Options are now: Options { amplify: 0.5, demo: true }
lua | Options from rust: { amplify = 579, demo = true }
```

- **⛔ with f32 (case 2)**: In some instance the returned Dictionary from rust is missing the f32 field in lua:

```sh
lua | Options before rust: { amplify = 0.5, demo = true }
rust | Merging default options with other: OptionsOpt { amplify: Some(0.5), demo: Some(true) }
rust | Options are now: Options { amplify: 0.5, demo: true }
lua | Options from rust: { demo = true }
```

- **✅ With f64**:
```sh
lua | Options before rust: { amplify = 0.5, demo = true }
rust | Merging default options with other: OptionsOpt { amplify: Some(0.5), demo: Some(true) }
rust | Options are now: Options { amplify: 0.5, demo: true }
lua | Options from rust: { amplify = 0.5, demo = true }
```

**Comment by noib3** [comment]
Yes this is expected, unfortunately we use `f32` to [represent functions](https://github.com/noib3/nvim-oxi/blob/36a59de62059311649e0f5a3a9ac7968cf72007c/crates/types/src/serde/de.rs#L57-L63).

**Comment by melMass** [comment]
Thanks not a big deal in my case but I think it should be mentioned somewhere :)
