### ISSUE TITLE
"Validation complete used without nargs" error on stable

### ISSUE THREAD

**Issue by melMass** [noib3/nvim-oxi#154]
Hi,

I can provide more info/context soon but I just wanted to log it already in case anyone has a clue.
I have a [toy project](https://github.com/melMass/echo.nvim) to test out nvim-oxi and the current version compiles fine for either nightly or stable.

I'm now adding a custom command:

```rust
let opts = CreateCommandOpts::builder()
        .bang(true)
        .desc("play audio using echo.nvim")
        .nargs(CommandNArgs::ZeroOrOne)
        .build();
```

And since then the stable build errors out with the title of this issue, nightly still works fine:

<img src="https://github.com/noib3/nvim-oxi/assets/7041726/7fe6b77a-aec6-4417-88c0-5848d7e361fc" width=400/>

**Comment by noib3** [comment]
Hi, sorry for the glacially slow reply. I've just tried reproducing this [here](https://github.com/noib3/nvim-oxi/blob/main/tests/src/api/command.rs#L21-L29), but the test passes on 0.9, 0.10 and Nightly.

I think this got fixed somewhere along the way. If you still experience this, consider opening a new issue.
