### ISSUE TITLE
Api nvim_cmd not working

### ISSUE THREAD

**Issue by Norlock** [noib3/nvim-oxi#157]
The following command crashes Neovim for me with a SIGSEGV:

```rust
api::cmd(
    &CmdInfos::builder().cmd("echo").args(vec!["123"]).bang(false).build(),
    &CmdOpts::default(),
)?;
```

I'm using the nightly version on:
```
NVIM v0.10.0-dev-2849+g4946489e2
Build type: RelWithDebInfo
LuaJIT 2.1.1710088188
```

Code: 
https://github.com/Norlock/nvim-traveller-rs/tree/bug/nvim_cmd

**Comment by noib3** [comment]
Yes, our nightly is not up to date with Neovim. I have a [PR](https://github.com/noib3/nvim-oxi/pull/134) open that I'll try to merge this weekend.

**Comment by Norlock** [comment]
Ok nice! After I finish my plugin, I maybe can create some mlua bindings like `vim.fn.getcwd` and other functions, or do you prefer using the C binding for that? Because I'm not really good with those.
