### ISSUE TITLE
Not possible to use this repo's HEAD commit as a dependency

### ISSUE THREAD

**Issue by myypo** [noib3/nvim-oxi#178]
Since `0.5.0` release it is no longer possible to use the latest commit of this repo. The following snippet in `Cargo.toml` dependencies will bring in version `0.5.0` of the workspace crates instead of the HEAD. 
```toml
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi", features = ["neovim-0-10", "test"] }
```

It was caused by [this update to Cargo.toml](https://github.com/noib3/nvim-oxi/commit/e6d3733a6f63b9e82f4801ac0e815af231599393#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542)  

Would it be ok to revert this change? On the first glance dependencies with relative paths does not seem to be a problem to me since the version on crates io will be pinned either way?

**Comment by noib3** [comment]
Cargo forces you to spell out the version when publishing to `crates.io`, but I forgot to turn those back into relative paths. I just did (ff436db225abcc6b7c8e05055602e792325fbd67). I also published `v0.5.1`, so you can use that instead of HEAD.
