### ISSUE TITLE
A `format!` like macro to create `nvim_oxi::String`s

### ISSUE THREAD

**Issue by SCJangra** [noib3/nvim-oxi#184]
Currently, to create formatted `nvim_oxi::String`s, we first need to create an `std` string, and then convert that to `nvm_oxi::String`. That's two allocations where ideally only one should be necessary. This is important for example when passing a large number of formatted strings to `Buffer::set_lines`.

**Comment by SCJangra** [comment]
I'd be happy to create a PR if you're open to merging it.

**Comment by noib3** [comment]
Yes, I'd merge a `nvim_oxi::string!` macro that produces `nvim_oxi::String`s.

**Comment by SCJangra** [comment]
Great, I'll try to do it this weekend.
