### ISSUE TITLE
error E5108: The specified procedure could not be found (windows)

### ISSUE THREAD

**Issue by dwexel** [noib3/nvim-oxi#185]
Error when calling `require("...")` from lua

steps to reproduce
1. create cargo package

```
[package]
name = "test"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nvim-oxi = { version = "0.5.1", features = ["neovim-0-10"] }
```

2. create `src\lib.rs` with this code

```
use nvim_oxi::{Dictionary, Function, Object};

#[nvim_oxi::plugin]
fn calc() -> Dictionary {
    let add = Function::from_fn(|(a, b): (i32, i32)| a + b);

    let multiply = Function::from_fn(|(a, b): (i32, i32)| a * b);

    let compute = Function::from_fn(
        |(fun, a, b): (Function<(i32, i32), i32>, i32, i32)| {
            fun.call((a, b)).unwrap()
        },
    );

    Dictionary::from_iter([
        ("add", Object::from(add)),
        ("multiply", Object::from(multiply)),
        ("compute", Object::from(compute)),
    ])
}
```

3. compile `test.dll` as `--release` and move it to `lua/test.dll`
4. from neovim, run

```
:set rtp+=~/Desktop/test
:lua =require("test")
```

error

![image](https://github.com/user-attachments/assets/d5909819-ef3f-4d7b-8a42-d46132d88ab0)

this error doesn't happen when `lua/test.lua` exists rather than `lua/test.dll`
thanks for help!

**Comment by SCJangra** [comment]
Try renaming your function from `calc` to `test`. As far as I know, the function that `#[nvim_oxi::plugin]` is applied to must have the same name as the package name.

**Comment by dwexel** [comment]
> Try renaming your function from `calc` to `test`. As far as I know, the function that `#[nvim_oxi::plugin]` is applied to must have the same name as the package name.

yes this worked! thank you!!

**Comment by SCJangra** [comment]
If your problem is resolved, then you should close the issue.
