### ISSUE TITLE
'{ expected "integer", actual "luaref" }' error using Buffer::call

### ISSUE THREAD

**Issue by UpsideDownFoxxo** [noib3/nvim-oxi#193]
I'm trying to call the "byte2line" function using nvim_oxi.
```rust
let line = nvim_oxi::api::call_function(
    "byte2line",
    nvim_oxi::Array::from_iter([byte_offset]),
);
```

This works as expected. But trying to run the function inside a Buffer call, as below, gives me a conversion error:
```rust
let line = buf.call(move |_| {
        nvim_oxi::api::call_function(
            "byte2line",
            nvim_oxi::Array::from_iter([byte_offset]),
    )
});
```
`line` is now always an Err with the `ObjectConversion(FromWrongType { expected: "integer", actual: "luaref" })` value. 
How can I fix this issue?

I'm using the nvim_oxi 5.1 crate

**Comment by noib3** [comment]
I'm investigating this. I don't think it has anything to do w/ `byte2line`; I was able to reproduce the bug with:

```rust
#[nvim_oxi::plugin]
fn test() {
    nvim_oxi::print!("42 is: {:?}", nvim_oxi::api::Buffer::current().call(|_| 42));
}
```

Which prints `42 is: Err(ObjectConversion(FromWrongType { expected: "integer", actual: "luaref" }))` on both 0.10.2 and Nightly.

**Comment by noib3** [comment]
Try building your crate against `nvim-oxi's `main`, this should be resolved.
