### ISSUE TITLE
Support for launching terminal processes

### ISSUE THREAD

**Issue by dasupradyumna** [noib3/nvim-oxi#198]
I do not see support for launching processes in terminal buffers similar to `termopen()` or `jobstart()` from neovim.
I may be unaware of existing support ; if so, could anyone point me to the right item to use?

I would appreciate help on this front since it is essential to a plugin I am developing.

**Comment by noib3** [comment]
Does [`call_function()`](https://docs.rs/nvim-oxi/0.5.1/nvim_oxi/api/fn.call_function.html) not work for your use case?

**Comment by dasupradyumna** [comment]
Ah yes, I don't know how I missed this. Let me try this out!
Thank you for the quick reply :)

**Comment by dasupradyumna** [comment]
That served my purposes, thank you for the quick reply!
