### ISSUE TITLE
No conversion support for builtin String type into nvim-oxi types

### ISSUE THREAD

**Issue by dasupradyumna** [noib3/nvim-oxi#200]
Hello @noib3,

I am trying to build a `Dictionary` instance from a `HashMap<String, String>` by creating an iterator, and I'm facing the below compiler errors. Can you tell me why most Rust builtin types have been provided conversion support to `nvim_oxi::Object` or `nvim_oxi::String`, but not the builtin `std::string::String` ?

![image](https://github.com/user-attachments/assets/8ee99921-f3d9-4ed0-88ef-477bbd17cfe5)

![image](https://github.com/user-attachments/assets/1e627c3e-71cc-443f-b2d2-83caf8e92e38)

Thank you for all your work on this project ~

**Comment by noib3** [comment]
`nvim_oxi::String` and `std::string::String` are not layout compatible, so if you want to convert one into the other you have to allocate. Most types are converted straight into `nvim_oxi::String`s to avoid allocating twice.

You can convert a `&str` into a `nvim_oxi::String` though, so if you have a `std::string::String` just dereference it.

**Comment by dasupradyumna** [comment]
I see, thank you for the explanation! :)

Could you elaborate further on what you mean by layout compatible?
Or point me to any resource where I can learn more about that?

**Comment by noib3** [comment]
https://doc.rust-lang.org/nomicon/other-reprs.html#reprc
https://doc.rust-lang.org/nomicon/ffi.html#interoperability-with-foreign-code
