### ISSUE TITLE
Unable to compute rhs in `nvim_buf_set_keymap`

### ISSUE THREAD

**Issue by airblast-dev** [noib3/nvim-oxi#209]
Based on the docs of `nvim_set_keymap`, the callback can return a string to compute the rhs if a callback is provided in the opts. 
See: https://neovim.io/doc/user/api.html#nvim_set_keymap()

Problem is [SetKeymapOptsBuilder::callback](https://docs.rs/nvim-oxi/0.5.1/nvim_oxi/api/opts/struct.SetKeymapOptsBuilder.html#method.callback) requires the function to return `()` which makes it so only the rhs provided in the function arguments can be used.

The same issue is also present on the methods buffer variant `nvim_buf_set_keymap`, and [SetKeymapOptsBuilder::callback](https://docs.rs/nvim-oxi/0.5.1/nvim_oxi/api/opts/struct.SetKeymapOptsBuilder.html#method.callback)

I think its best to return a `nvim_oxi::String` since the only other type we can return is `nil` which is equivalent to returning an empty string based on the docs.

**Comment by noib3** [comment]
> the callback can return a string to compute the rhs if a callback is provided in the opts

Where is this mentioned in the docs? I couldn't find anything about this under `:h nvim_{buf_}set_keymap`.

**Comment by airblast-dev** [comment]
```
• {opts}  Optional parameters map: Accepts all |:map-arguments| as keys
                except <buffer>, values are booleans (default false). Also:
                • "noremap" disables |recursive_mapping|, like |:noremap|
                • "desc" human-readable description.
                • "callback" Lua function called in place of {rhs}.
                • "replace_keycodes" (boolean) When "expr" is true, replace
                  keycodes in the resulting string (see
                  |nvim_replace_termcodes()|). Returning nil from the Lua
                  "callback" is equivalent to returning an empty string.
```
The callback is called in place of {rhs}.
However this section "Returning nil from the Lua callback is equivalent to returning an empty string." tells me that a returned string is used as {rhs}. After testing it I think I was incorrect. Though I am not exactly sure what is meant by this section.

Regardless I apologize for wasting your time as I think this was just me misunderstanding what the docs meant.

**Comment by noib3** [comment]
Can this be closed?

**Comment by airblast-dev** [comment]
Yes, pretty sure I misunderstood the docs.
