### ISSUE TITLE
`LuaFun::from_fn_mut` and `LuaFun::from_fn_once` are unsound

### ISSUE THREAD

**Issue by Maan2003** [noib3/nvim-oxi#28]
- use after move in `from_fn_once`:  if called twice, on second call, we call Box::from_raw is called on a value is that already moved in previous call.

https://github.com/noib3/nvim-oxi/blob/09d6934c343f556ec605be84d84e5c5086119282/nvim-oxi/src/lua/luafun.rs#L165-L172

--- 
- mutable aliasing in `from_fn_mut`: if called recursively, we create two mutable references to same closure.

https://github.com/noib3/nvim-oxi/blob/09d6934c343f556ec605be84d84e5c5086119282/nvim-oxi/src/lua/luafun.rs#L143-L150

**Comment by noib3** [comment]
There's no way to call neither of those functions more than once.

**Comment by Maan2003** [comment]
how is this guaranteed?

**Comment by noib3** [comment]
`from_fn`, `from_fn_mut` and `from_fn_once` all take ownership of the closures that get passed in, so to call them more than once you'd have to pass different closures (or clone a single closure, which is fine).

**Comment by Maan2003** [comment]
I didn't mean calling `from_fn_once` twice, but calling the lua function `from_fn_once` creates.
in pseudo code
```rust
// we create a LuaFun
let x = String::new();
let closure = LuaFun::from_fn_once(move || drop(x));
// and pass it to neovim

// later in neovim code
closure();
closure();
```

**Comment by noib3** [comment]
Ah yes, this is what the `LuaFun::call` method would do, which is still unimplemented. A couple of notes:

- calling a `LuaFun` created from a `FnMut` more than once is fine, those created w/ `FnOnce` are problematic;
- we only accept a `FnOnce` in the api when we know Neovim is only gonna call that function once. For example `Buffer::call` or `nvim_oxi::schedule` accept an `FnOnce`;
- regarding the `call` method, I'm still unsure on how to go about it. In the previous implementation where I hade three separate structs, i.e. `LuaFn`, `LuaFnMut` and `LuaFnOnce` the `call` method was acting on `&self`, `&mut self` and `self` respectively.

What I'm probably going to do is change the visibility of the `LuaFun::from_fn_once` method to only make it available inside the crate, and remove the `ToObject` implementation for boxed `FnOnce` closures [here](https://github.com/noib3/nvim-oxi/blob/09d6934c343f556ec605be84d84e5c5086119282/nvim-oxi/src/object/to_object.rs#L124).

**Comment by Maan2003** [comment]
My solution would be to just provide a `from_fn`.

`FnOnce` can just be transformed into `FnMut` and `FnMut` can be transformed into a `Fn` using

```rust
fn fn_mut_to_fn(f: impl FnMut()) -> impl Fn() {
    let f = RefCell::new(f);
    move || {
        (f.try_borrow_mut().expect("FnMut called recursively"))();
    }
}

fn fn_once_to_fn_mut(f: impl FnOnce()) -> impl FnMut() {
    let mut f = Some(f)
    move || {
        (f.take().expect("FnOnce called more than once"))();
    }
}
```

**Comment by noib3** [comment]
What's there to gain by only having a `from_fn` method? Using `RefCell` forces you to add an unnecessary layer of indirection. Making `from_fn_once` private is enough to prevent users from creating `LuaFun`s from `FnOnce` closures, and creating a `LuaFun` from an `FnMut` closure is totally fine.

**Comment by Maan2003** [comment]
Safety.

In terms of performance, RefCell just costs a single integer arithmetic, and the branch would always be predicted correctly.

**Comment by Maan2003** [comment]
> creating a LuaFun from an FnMut closure is totally fine.

no

```rust
let mut x = None;
LuaFun::from_mut(move || {
    match x {
         Some(x) => {
                x = None;
         }
         None => {
                x = Some(5);
                let borrow  = x.as_mut().unwrap();
                // call some neovim apis
                // neovim calls this function again recursively
  
                // borrow is a reference to invalid memory, because the call to this closure set it to x to None.
                *borrow = 6;
         }
    }
});
// pass to neovim
```

**Comment by noib3** [comment]
> neovim calls this function again recursively

I'm not sure what you mean by "recursively", Neovim doesn't really call any function recursively. I guess you meant "more than once"?

> borrow is a reference to invalid memory, because the call to this closure set it to x to None.

No. When the function gets called if `x` is Some it becomes `None` and if it's `None` it becomes `Some(6)`. Neither of those branches involve any references to invalid memory.

Test it for yourself:

```rust
use nvim_oxi::{
    self as nvim,
    api::{opts::*, Buffer},
    LuaFun,
};

#[nvim::module]
fn liboxi() -> nvim::Result<()> {
    let mut x = None::<u8>;
    let fun = LuaFun::from_fn_mut(move |_: CreateCommandArgs| {
        match x {
            Some(_) => {
                x = None;
            }
            None => {
                x = Some(5);
                let borrow = x.as_mut().unwrap();
                *borrow = 6;
            }
        }
        nvim::print!("{x:?}");
        Ok(())
    });

    let buf = Buffer::current();
    let opts = CreateCommandOpts::builder().build();
    let _ = buf.create_user_command("Foo", fun, &opts);

    Ok(())
}
```
 
Every time you call `:Foo` from Neovim you'll see either `Some(6)` or `None`.

**Comment by noib3** [comment]
Oh sorry now I see what you mean. I wonder if Neovim has some api that would cause this to happen, but using `RefCell` is not a solution here. You'd just get a panic instead.

**Comment by Maan2003** [comment]
> I wonder if Neovim has some api that would cause this to happen.

maybe `nvim_command("Foo")`

> Still, using RefCell doesn't help much. You'd just get a panic instead.

panic is still a lot better than segfaults.

**Comment by noib3** [comment]
> panic is still a lot better than segfaults.

fair enough.

I still think we should keep `LuaFun::from_fn_mut`, just turn the `FnMut` into an `Fn` via `RefCell` and have it call `from_fn`. Same for `from_fn_once`. We should also add two variants to `Error` that we can return instead of panicking, say `LuaFunMutRecursiveCallback` and `LuaFunOnceMoreThanOnce`. Idk I'm bad at names. Will accept a PR if you want to go at it.

**Comment by Maan2003** [comment]
But where and how do we return the error?

**Comment by noib3** [comment]
```rust
pub fn from_fn_mut<F>(fun: F) -> Self
where
    F: FnMut(A) -> Result<R> + 'static,
{
    let fun = RefCell::new(fun);
    Self::from_fn(move |args| {
        fun.try_borrow_mut()
            .map_err(|_| crate::Error:: LuaFunMutRecursiveCallback)?(
            args
        )
    })
}
```

**Comment by Maan2003** [comment]
wow, I didn't realize that from_fn handled Results already

**Comment by Maan2003** [comment]
also this is exactly what I meant in #26 . We end up re inventing and re implementing what [mlua already has](https://github.com/khvzak/mlua/blob/d9ac7abff2d605f8345657b1625eb3e2de02ddd8/src/lua.rs#L1564-L1568)

**Comment by noib3** [comment]
Yes, there's some overlap but not nearly enough to justify having it as a dependency. `mlua` is 13k+ loc, our `lua` module is ~500 loc and won't grow much past that. Also, the `mlua` api is fundamentally incompatible with ours.
