### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by kkharji** [noib3/nvim-oxi#35]
Hey @noib3, I'm in the middle of refactoring out neovim logic from Xmas core, and I thought I might give nvim-oxi a try. Though unfortunately it isn't publish yet to crate io and current version is at 0.0.0 which a bit odd don't you think? or is it saying don't used me 🤣. Anyways I'm browse through the codebase right now, amazing progress so far, congrats

**Comment by tami5** [comment]
I don't want to make your life harder but `#![deny(missing_docs)]` needs to be at lib.rs files 🌝. Also,

```rust
#![deny(future_incompatible)]
#![deny(nonstandard_style)]
#![deny(rustdoc::broken_intra_doc_links)]
#![doc = include_str!("../../README.md")]
```

**Comment by noib3** [comment]
> or is it saying don't used me

Yep. Publishing to crates.io is the next big milestone but we're not there yet.

Btw, if all you need are the functions listed under `:h api-buffer` and `:h api-global` you could already use oxi as those are already implemented (though documentation is still pretty thin).

**Comment by noib3** [comment]
@tami5 every single function in the `vim.api` Lua table has been implemented. Will probably spend the next 2/3 weeks adding docs and testing the code more thoroughly before releasing on crates.io.

Would appreciate if you could test `nvim-oxi` in your project to get some feedback. You can use the crate by specifying the GitHub path in your `Cargo.toml`, e.g.
```
nvim-oxi = { git = "https://github.com/noib3/nvim-oxi/tree/master/nvim-oxi" }
```

For some code examples you can look at the [oxi-tests](https://github.com/noib3/nvim-oxi/tree/master/oxi-tests/src/api) crate.

**Comment by tami5** [comment]
> @tami5 every single function in the `vim.api` Lua table has been implemented. Will probably spend the next 2/3 weeks adding docs and testing the code more thoroughly before releasing on crates.io.
> 
> 
> 
> Would appreciate if you could test `nvim-oxi` in your project to get some feedback. You can use the crate by specifying the GitHub path in your `Cargo.toml`, e.g.
> 
> ```
> 
> nvim-oxi = { git = "https://github.com/noib3/nvim-oxi/tree/master/nvim-oxi" }
> 
> ```
> 
> 
> 
> For some code examples you can look at the [oxi-tests](https://github.com/noib3/nvim-oxi/tree/master/oxi-tests/src/api) crate.

Hey @noib3, I looked it up the example, and it looks absolutely amazing, I really would want to do another refactor to oxi now I'm basically using block_on on every async func with mlua, how every unfortunately I'm feedup at the moment and there are pending tasks that need to attend to, however feel free to fork the project , I really want to rm lua/xbase and have everything in rust.

**Comment by noib3** [comment]
@tami5 can you post a minimal but complete example of how you're using async functions w/ Neovim? I might work on it this weekend.

**Comment by tami5** [comment]
> @tami5 can you post a minimal but complete example of how you're using async functions w/ Neovim? I might work on it this weekend.

nah, no need, I'm using basically what you've written in complete, loop pipes. For the requests I'm just using RUNTIME.block_on.

**Comment by noib3** [comment]
https://crates.io/crates/nvim-oxi

**Comment by kkharji** [comment]
🎉 awesome work @noib3

**Comment by turboladen** [comment]
> 🎉 awesome work @noib3 

I concur! 👏👏👏
