### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by shift-d** [noib3/nvim-oxi#37]
Since `0.1` release is out, there is a very simple question mentioned inside the issue's title. Is the project being put at the bug-maintenance mode? Or some features are still planned?

**Comment by noib3** [comment]
The next big feature is async support, I've just opened an [new issue](#38) about it.

Other than that I'd like to spend the coming weeks focusing back on `nvim-compleet`, fixing bugs in `nvim-oxi` as I find them and adding better documentation along the way. Of course, if anyone wants to work on #38 I'd be glad to review any PRs.
