### ISSUE TITLE
Support for Lua API's  opt manipulation

### ISSUE THREAD

**Issue by ModProg** [noib3/nvim-oxi#39]
I'm not sure whether it is possible to implement this in here as it is only part of the lua API if I understand correctly, but they have a really convenient way to interact with option values using e.g. `append`, `prepend`...

I want to migrate from my own nvim plugin library, which was purely based on the lua api, which had these features therefor, to `nvim-oxi` as it seems to provide way better ergonomics.

But I would be glad if I could somehow get access to the `vim.opts` that is available from lua: [example in my API](https://nvim.docs.modprog.de/struct.Vim.html#method.opt).

**Comment by noib3** [comment]
It's technically possible but it's outside the scope of the project.

The `vim.opt` functionalities are built on top of [`nvim_set_option_value`](https://docs.rs/nvim-oxi/latest/nvim_oxi/api/fn.set_option_value.html) to have a more ergonomic way to configure options, which is mostly intended for end users.
