### ISSUE TITLE
With `set_hl` `.underline()` doesn't seem to be working

### ISSUE THREAD

**Issue by shaunsingh** [noib3/nvim-oxi#49]
Hi, currently just messing around with `nvim-oxi`. Thanks for the awesome project!

<img width="382" alt="image" src="https://user-images.githubusercontent.com/71196912/181878842-6779edfa-1454-4592-9260-c682a90be677.png">

As you can see the matched parenthesis should have a small underline underneath it, but it doesn't. 

If it helps, `.bold()` and `.italic()` both seem to work fine

**Comment by noib3** [comment]
What version of Neovim are you on? Does your terminal support underline?

**Comment by shaunsingh** [comment]
> What version of Neovim are you on?

`v0.8.0` (nightly), though the issue is reproducible on `v0.7.0` as well. 

> Does your terminal support underline?

Yup, tested with alacrity & neovide

> :hi MatchParen

<img width="403" alt="image" src="https://user-images.githubusercontent.com/71196912/181908702-4dfae739-bf57-495e-a80a-db8910872b2b.png">

>  Does it work if you do it from Lua?

Yup, `nvim_set_hl` from lua works just fine.

**Comment by noib3** [comment]
If you're using nightly you should add the `nightly` feature as described [here](https://github.com/noib3/nvim-oxi/issues/43#issuecomment-1199078348).

I [can't reproduce](https://github.com/noib3/nvim-oxi/commit/a3bbae41326ae4ffcb336dc1f75537058d7d55f4) this on 0.7, I've also tested it manually with a clean Neovim config (`nvim -u NONE`) and everything works as expected. I believe something else is resetting your highlight of `MatchParen` *after* you load the Rust module.

**Comment by shaunsingh** [comment]
I'll poke around and see whats causing it, thanks for looking into it! This is such a nice crate to work with
