### ISSUE TITLE
Got fatal issue when creating user command

### ISSUE THREAD

**Issue by Avimitin** [noib3/nvim-oxi#58]
After loading the .so library and call it from neovim, the neovim crash and report that:

```text
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NvimError("keepscript is not a boolean")'
```

My neovim version:

```text
NVIM v0.8.0-dev-1146-g7a70e9587c
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3
```

Example code: https://github.com/Avimitin/cargo-add-cmp.nvim/blob/master/src/lib.rs#L123-L137

**Comment by noib3** [comment]
Make sure to use to add `features = ["nightly"]` to your `Cargo.toml` if you're using a Nightly version of Neovim.

**Comment by Avimitin** [comment]
Thanks for your reply.

**Comment by Avimitin** [comment]
```text
error[E0425]: cannot find value `KeyDict_cmd_opts` in this scope
  --> /home/sh1marin/.cargo/registry/src/github.com-1ecc6299db9ec823/nvim-oxi-0.1.3/src/api/vimscript.rs:65:25
   |
65 |     let opts = opts.map(KeyDict_cmd_opts).unwrap_or_default();
   |                         ^^^^^^^^^^^^^^^^ not found in this scope
```

However after I adding the nightly features the nvim-oxi itself can't be compiled. I am using nvim-oxi v0.1.3.

**Comment by Avimitin** [comment]
It seems like it has been fixed in https://github.com/noib3/nvim-oxi/commit/2a7e8acc18b05ea47264cefda87ad92e8048699d, but is not included in the latest version.

**Comment by Avimitin** [comment]
I pull the latest code from git repo and it can be built succesfully. Waiting for the new version released.
