### ISSUE TITLE
LuaPushable does not impl for Vec<T>

### ISSUE THREAD

**Issue by Avimitin** [noib3/nvim-oxi#59]
The custom completion list function require a type `Function<(String, String, usize), Vec<String>>`: https://docs.rs/nvim-oxi/latest/nvim_oxi/types/enum.CommandComplete.html#variant.CustomList. However the trait LuaPushable doesn't implemented for Vec, so I can't create a new function that have return type `Result<Vec<T>>`.

```text
121 |     let completion = Function::from_fn(generate_completion);
    |                      ^^^^^^^^^^^^^^^^^ the trait `LuaPushable` is not implemented for `Vec<std::string::String>`
```

My function signature: `fn generate_completion(arguments: (String, String, usize)) -> Result<Vec<String>>`

Build with `rev=e5c34c7`, which is currently the HEAD of the git repo.

**Comment by noib3** [comment]
done 86280aa35bc919334d227bc722c7ca92a3279cec
