### ISSUE TITLE
Unsafety when calling functions from other threads

### ISSUE THREAD

**Issue by oberblastmeister** [noib3/nvim-oxi#71]
`unwrap_unchecked` is used in `with_state` https://github.com/noib3/nvim-oxi/blob/master/crates/luajit-bindings/src/state.rs#L21. `with_state` is used in a bunch of safe functions such as `schedule`. So isn't it unsafe to call functions like `schedule` from other threads? I think the normal `unwrap` should be used here. The same thing happens in `libuv-bindings`

**Comment by noib3** [comment]
thanks for the catch, fixed by 87292165fc135fbbeede343683849096bb8cdc46
