### ISSUE TITLE
can i get the diagnostic table?

### ISSUE THREAD

**Issue by yotam5** [noib3/nvim-oxi#75]
![image](https://user-images.githubusercontent.com/69643410/196746025-e0be930d-faef-4507-96c8-cffaa9fc411e.png)

hey im trying to figure out how can i get the diagnostic table, can it be done in the way above with some changes?
or is there other way to do so, it there are.
thanks

**Comment by noib3** [comment]
You're first putting `vim.diagnostic` on the Lua stack then popping `diagnostic` off, which doesn't do much.

I'd suggest to add bindings to the functions stored inside the `vim.diagnostic` table instead of the table itself.

**Comment by yotam5** [comment]
> You're first putting `vim.diagnostic` on the Lua stack then popping `diagnostic` off, which doesn't do much.
> 
> I'd suggest to add bindings to the functions stored inside the `vim.diagnostic` table instead of the table itself.

can you give a simple snippet of this?
im trying to understand the way the pop in the Poppable interface working, from my understanding you already implemented this for generic stuff like HashMap and Vec in poppable.rs,  what i dont understand is how i get the the diagnostic Table, i tried to pop it to a HashMap of Str,Str but obviously this is not how it intends to be, so i dont understand how to get it into a Dictionary.
I thought of using Mlua to do so i tried it before but i found your module way better for neovim functions instead or Mlua get("vim")? and etc every time

**Comment by noib3** [comment]
I've [added](6193b9d51e742b562d4f99630da6229c12e49a55) a `nvim_diagnostic` crate with a **very** rough (and totally untested) implementation of a binding to `vim.diagnostic.enable`. That should give you a general idea of what other bindings might look like.

**Comment by yotam5** [comment]
i think i got the gist of it, now im reading about the lua/c api to get a better understanding and its a weird one tbh.

![image](https://user-images.githubusercontent.com/69643410/196893366-e551c866-eeaf-4fe7-993c-c686c192cfb0.png)

im playing with some stuff now and found the code above to work, what im trying to figure out is how do i return a table? let say i want to return the table vim.diagnostic or any other table from lua to rust  without using mlua for now, either a copy or a reference.
