### ISSUE TITLE
Windows Requirements?

### ISSUE THREAD

**Issue by ModProg** [noib3/nvim-oxi#77]
Trying to set up my CI on an nvim-oxi plugin, but linking fails: https://github.com/ModProg/config.nvim/actions/runs/3302333877

I see you have removed windows building from the CI in this repo. But do you know what the requirements for building for windows are?

**Comment by noib3** [comment]
I'm actually not sure what's the issue with building on Windows. I'm on macOS atm so I have no way to test it, if someone using Windows can chime in that'd be great.

**Comment by n-shift** [comment]
IIRC this was solvable via downloading luajit libraries on windows and specifying the path to them. It is managed automatically on unix via pkg-config. Will try to solve this one soon.

**Comment by n-shift** [comment]
wip

**Comment by n-shift** [comment]
You might have noticed that PR is quite stale. I am having some health issues right now and I just can't get myself to coding at the moment. I will continue working on it once I'm good.

**Comment by tan-wei** [comment]
Hmm, the issue stil exists. Link error 1181

**Comment by searleser97** [comment]
All is needed is to add this to your `<project>/.cargo/config` apparently 

https://github.com/noib3/nvim-oxi/pull/85/commits/8cd705710b928efcdbd76362c0ee77fd0339780b

**Comment by noib3** [comment]
Closed by #149.
