### ISSUE TITLE
Add a neovim actor

### ISSUE THREAD

**Issue by oberblastmeister** [noib3/nvim-oxi#79]
I think this pattern, creating a `AsyncHandle` with a channel and sending messages to the channel while notifying the `AsyncHandle`, will be a pretty common pattern when creating plugins. It is used in both your `nvim-completion` plugin and my own plugin. Whenever a plugin needs multithreading, this pattern will be needed to interact with `nvim`. I think it would be good to reduce the boilerplate when creating new plugins.

**Comment by noib3** [comment]
I'm not sure what boilerplate you're referring to. In `nvim-completion` I'm using a [custom message sender](https://github.com/noib3/nvim-completion/blob/3ad95e2c766f900c46e09c65357bc3bab6519c12/completion-types/src/core_message.rs#L25) that encapsulates a tokio `UnboundedSender` and an `AsyncHandle` to [automatically notify Neovim](https://github.com/noib3/nvim-completion/blob/3ad95e2c766f900c46e09c65357bc3bab6519c12/completion-types/src/core_message.rs#L50) when a message is sent.

**Comment by oberblastmeister** [comment]
Yes, that is exactly what I am referring to.

**Comment by noib3** [comment]
That's like 10 lines of code, plugins can easily handle that themselves.

**Comment by oberblastmeister** [comment]
That true, imposing the kind of channel might be bad.
