### ISSUE TITLE
Consider adding examples regarding multiple arguments, but arguments are integers

### ISSUE THREAD

**Issue by K0dikas** [noib3/nvim-oxi#83]
I've implemented a silly built-in calculator in Neovim that accepts two arguments in `cmdline`, and the arguments could be `i32` or `i64`. My basis would be your `calc.rs` example, problem is, is that it's not a user command. I have tried different ways and this is what I came up with:

    use nvim_oxi::api::{self, opts::*, types::*};
    use nvim_oxi::{self as oxi, print};

         #[oxi::module]
         fn print() -> oxi::Result<i32> {

    let opts = CreateCommandOpts::builder()
        .bang(true)
        .desc("shows a greetings message")
        .nargs(CommandNArgs::OneOrMore)
        .build();

    let addition = |args: CommandArgs| {

        let num1: i64 = args.args.expect("Can't convert to i64").parse().unwrap();
        print!("The sum is: {}", num1 + num1);
        Ok(())
    };

    api::create_user_command("Add", addition, &opts)?;

    Ok(0)
    }

It compiles successfully. Input in the `cmdline` should be something like this `:Add 10 10`, this would add the two arguments and the result would be `20`, but it came as `ParseIntError`. If my input is like this `:Add 50`, then the result would be `100` because `num1` added itself, and I don't want it that way. Could you add another example regarding this issue that I'm facing?

**Comment by noib3** [comment]
Do you have an example of an equivalent Lua script that does what you want?

**Comment by K0dikas** [comment]
I actually did a sketch for my basis before I do the exact same thing in Rust, looks like this;

    vim.api.nvim_create_user_command(
	'Add',
	    function(num)
		 local sum = 0
		 for _, arg in ipairs(num.fargs) do
	             sum = sum + tonumber(arg)
	         end

	        print(sum)
    end,
	        { nargs = '*' }
    )

I remember seeing a calculator in neovim using the `cmdline`, but it's using Rust and Vimscript https://github.com/srishanbhattarai/neovim-calculator . I feel like it's the exact same thing on what to do in Rust

**Comment by K0dikas** [comment]
Subtraction, Multiplication, and Division are different since they don't always give the same result whatever order the values are in, `non-commutative` in mathematics. So the code will change into something like this:

    vim.api.nvim_create_user_command(
    'Subtract',
        function(num)
            local diff
		for i, arg in ipairs(num.fargs) do
			diff = (i == 1) and tonumber(arg) or diff - tonumber(arg)

	    end
	print("The difference is:", diff)

    end,
	{ nargs = '*' }
    )

**Comment by noib3** [comment]
Porting your Lua code to the Rust equivalent seems to be pretty straightforward:

```rust
use nvim_oxi as oxi;
use oxi::api::{self, opts::*, types::*};

#[oxi::module]
fn oxi() -> oxi::Result<()> {
    let opts = CreateCommandOpts::builder()
        .nargs(CommandNArgs::OneOrMore)
        .build();

    let add = |args: CommandArgs| {
        let sum = args
            .fargs
            .into_iter()
            .filter_map(|s| s.parse::<f64>().ok())
            .sum::<f64>();

        oxi::print!("{}", sum);

        Ok::<_, api::Error>(())
    };

    api::create_user_command("Add", add, &opts)?;

    Ok(())
}
```

-> 

```
:Add 1 2
3
```
