### ISSUE TITLE
Buffer.set_text() does not play nicely inside of a MutexGuard

### ISSUE THREAD

**Issue by pashneal** [noib3/nvim-oxi#99]
Will have more updates later soon, just adding this while I investigate the issue and produce minimal code replicating it.

**Comment by noib3** [comment]
Did you manage to replicate this?

**Comment by pashneal** [comment]
Yep, give me until Mar 30th to clean up and throw the code here, I was also trying to investigate the source of the bug but alas.

**Comment by pashneal** [comment]
Unable to replicate using minimal after updating, closing for now!
